name: Docker Deploy & Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t simple-express-app .

      - name: Run Docker Container
        run: |
          docker run -d --name test-container -p 3000:3000 simple-express-app
          # Wait a few seconds for the container to start up
          sleep 5

      - name: Test GET Request
        run: |
          echo "Testing GET request..."
          curl -v http://localhost:3000/

      - name: (Optional) Test POST Request
        run: |
          echo "Testing POST request..."
          curl -X POST -H "Content-Type: application/json" -d '{"key":"value"}' http://localhost:3000/

      - name: Stop and Remove Container
        run: docker stop test-container && docker rm test-container
